"""Phase 2: customers, service_items, drysuit_details, inventory, price_list, tags

Revision ID: 46a737a590f6
Revises: 65a0d287ea08
Create Date: 2026-03-05 00:25:17.882040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a737a590f6'
down_revision = '65a0d287ea08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_list_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('tag_group', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index('ix_tags_tag_group', ['tag_group'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_type', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_primary', sa.String(length=20), nullable=True),
    sa.Column('phone_secondary', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('preferred_contact', sa.String(length=20), nullable=False),
    sa.Column('tax_exempt', sa.Boolean(), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('do_not_service', sa.Boolean(), nullable=False),
    sa.Column('do_not_service_reason', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('referral_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('ix_customers_business_name', ['business_name'], unique=False)
        batch_op.create_index('ix_customers_email', ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index('ix_customers_last_first', ['last_name', 'first_name'], unique=False)

    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('manufacturer_part_number', sa.String(length=100), nullable=True),
    sa.Column('purchase_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('resale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('markup_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('reorder_quantity', sa.Integer(), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_for_resale', sa.Boolean(), nullable=False),
    sa.Column('preferred_supplier', sa.String(length=255), nullable=True),
    sa.Column('supplier_url', sa.String(length=500), nullable=True),
    sa.Column('minimum_order_quantity', sa.Integer(), nullable=True),
    sa.Column('supplier_lead_time_days', sa.Integer(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index('ix_inventory_category_sub', ['category', 'subcategory'], unique=False)
        batch_op.create_index('ix_inventory_is_active', ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index('ix_inventory_stock_reorder', ['quantity_in_stock', 'reorder_level'], unique=False)

    op.create_table('price_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_tier', sa.String(length=50), nullable=True),
    sa.Column('is_per_unit', sa.Boolean(), nullable=False),
    sa.Column('default_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_label', sa.String(length=50), nullable=False),
    sa.Column('auto_deduct_parts', sa.Boolean(), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['price_list_categories.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('taggables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('taggable_type', sa.String(length=50), nullable=False),
    sa.Column('taggable_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'taggable_type', 'taggable_id', name='uq_taggable_unique')
    )
    with op.batch_alter_table('taggables', schema=None) as batch_op:
        batch_op.create_index('ix_taggable_type_id', ['taggable_type', 'taggable_id'], unique=False)

    op.create_table('price_list_item_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_list_item_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['price_list_item_id'], ['price_list_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('item_category', sa.String(length=100), nullable=True),
    sa.Column('serviceability', sa.String(length=30), nullable=False),
    sa.Column('serviceability_notes', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year_manufactured', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_service_date', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    with op.batch_alter_table('service_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_items_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index('ix_service_items_serial_number', ['serial_number'], unique=False)

    op.create_table('drysuit_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_item_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('material_type', sa.String(length=100), nullable=True),
    sa.Column('material_thickness', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('suit_entry_type', sa.String(length=50), nullable=True),
    sa.Column('neck_seal_type', sa.String(length=50), nullable=True),
    sa.Column('neck_seal_system', sa.String(length=100), nullable=True),
    sa.Column('wrist_seal_type', sa.String(length=50), nullable=True),
    sa.Column('wrist_seal_system', sa.String(length=100), nullable=True),
    sa.Column('zipper_type', sa.String(length=100), nullable=True),
    sa.Column('zipper_length', sa.String(length=50), nullable=True),
    sa.Column('zipper_orientation', sa.String(length=50), nullable=True),
    sa.Column('inflate_valve_brand', sa.String(length=100), nullable=True),
    sa.Column('inflate_valve_model', sa.String(length=100), nullable=True),
    sa.Column('inflate_valve_position', sa.String(length=50), nullable=True),
    sa.Column('dump_valve_brand', sa.String(length=100), nullable=True),
    sa.Column('dump_valve_model', sa.String(length=100), nullable=True),
    sa.Column('dump_valve_type', sa.String(length=50), nullable=True),
    sa.Column('boot_type', sa.String(length=50), nullable=True),
    sa.Column('boot_size', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_item_id'], ['service_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drysuit_details')
    with op.batch_alter_table('service_items', schema=None) as batch_op:
        batch_op.drop_index('ix_service_items_serial_number')
        batch_op.drop_index(batch_op.f('ix_service_items_is_deleted'))

    op.drop_table('service_items')
    op.drop_table('price_list_item_parts')
    with op.batch_alter_table('taggables', schema=None) as batch_op:
        batch_op.drop_index('ix_taggable_type_id')

    op.drop_table('taggables')
    op.drop_table('price_list_items')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index('ix_inventory_stock_reorder')
        batch_op.drop_index(batch_op.f('ix_inventory_items_is_deleted'))
        batch_op.drop_index('ix_inventory_is_active')
        batch_op.drop_index('ix_inventory_category_sub')

    op.drop_table('inventory_items')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('ix_customers_last_first')
        batch_op.drop_index(batch_op.f('ix_customers_is_deleted'))
        batch_op.drop_index('ix_customers_email')
        batch_op.drop_index('ix_customers_business_name')

    op.drop_table('customers')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('ix_tags_tag_group')

    op.drop_table('tags')
    op.drop_table('price_list_categories')
    # ### end Alembic commands ###
