"""Phase 3-5: service_orders, service_order_items, service_notes, applied_services, parts_used, labor_entries, invoices, invoice_orders, invoice_line_items, payments, notifications

Revision ID: c3d4e5f6a7b8
Revises: 46a737a590f6
Create Date: 2026-03-04 21:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d4e5f6a7b8'
down_revision = '46a737a590f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # ------------------------------------------------------------------
    # 1. service_orders
    # ------------------------------------------------------------------
    op.create_table('service_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('assigned_tech_id', sa.Integer(), nullable=True),
    sa.Column('date_received', sa.Date(), nullable=False),
    sa.Column('date_promised', sa.Date(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.Column('date_picked_up', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('estimated_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rush_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_name', sa.String(length=200), nullable=True),
    sa.Column('approval_method', sa.String(length=20), nullable=True),
    sa.Column('picked_up_by_name', sa.String(length=200), nullable=True),
    sa.Column('pickup_notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['assigned_tech_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    with op.batch_alter_table('service_orders', schema=None) as batch_op:
        batch_op.create_index('ix_service_orders_status', ['status'], unique=False)
        batch_op.create_index('ix_service_orders_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('ix_service_orders_date_received', ['date_received'], unique=False)
        batch_op.create_index('ix_service_orders_assigned_tech_id', ['assigned_tech_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_orders_is_deleted'), ['is_deleted'], unique=False)

    # ------------------------------------------------------------------
    # 2. service_order_items
    # ------------------------------------------------------------------
    op.create_table('service_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('service_item_id', sa.Integer(), nullable=False),
    sa.Column('work_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('condition_at_receipt', sa.Text(), nullable=True),
    sa.Column('customer_approved', sa.Boolean(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('warranty_type', sa.String(length=20), nullable=False),
    sa.Column('warranty_start_date', sa.Date(), nullable=True),
    sa.Column('warranty_end_date', sa.Date(), nullable=True),
    sa.Column('warranty_notes', sa.String(length=500), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['service_orders.id'], ),
    sa.ForeignKeyConstraint(['service_item_id'], ['service_items.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'service_item_id', name='uq_order_service_item')
    )

    # ------------------------------------------------------------------
    # 3. service_notes
    # ------------------------------------------------------------------
    op.create_table('service_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_order_item_id', sa.Integer(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_order_item_id'], ['service_order_items.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_notes', schema=None) as batch_op:
        batch_op.create_index('ix_service_notes_order_item_id', ['service_order_item_id'], unique=False)

    # ------------------------------------------------------------------
    # 4. applied_services
    # ------------------------------------------------------------------
    op.create_table('applied_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_order_item_id', sa.Integer(), nullable=False),
    sa.Column('price_list_item_id', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('price_overridden', sa.Boolean(), nullable=False),
    sa.Column('customer_approved', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_order_item_id'], ['service_order_items.id'], ),
    sa.ForeignKeyConstraint(['price_list_item_id'], ['price_list_items.id'], ),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applied_services', schema=None) as batch_op:
        batch_op.create_index('ix_applied_services_order_item_id', ['service_order_item_id'], unique=False)
        batch_op.create_index('ix_applied_services_price_list_item_id', ['price_list_item_id'], unique=False)

    # ------------------------------------------------------------------
    # 5. parts_used
    # ------------------------------------------------------------------
    op.create_table('parts_used',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_order_item_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('applied_service_id', sa.Integer(), nullable=True),
    sa.Column('is_auto_deducted', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_cost_at_use', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price_at_use', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_order_item_id'], ['service_order_items.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['applied_service_id'], ['applied_services.id'], ),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parts_used', schema=None) as batch_op:
        batch_op.create_index('ix_parts_used_order_item_id', ['service_order_item_id'], unique=False)
        batch_op.create_index('ix_parts_used_inventory_item_id', ['inventory_item_id'], unique=False)

    # ------------------------------------------------------------------
    # 6. labor_entries
    # ------------------------------------------------------------------
    op.create_table('labor_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_order_item_id', sa.Integer(), nullable=False),
    sa.Column('tech_id', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['service_order_item_id'], ['service_order_items.id'], ),
    sa.ForeignKeyConstraint(['tech_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('labor_entries', schema=None) as batch_op:
        batch_op.create_index('ix_labor_entries_order_item_id', ['service_order_item_id'], unique=False)
        batch_op.create_index('ix_labor_entries_tech_id', ['tech_id'], unique=False)
        batch_op.create_index('ix_labor_entries_work_date', ['work_date'], unique=False)

    # ------------------------------------------------------------------
    # 7. invoices
    # ------------------------------------------------------------------
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('balance_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('external_system', sa.String(length=50), nullable=True),
    sa.Column('external_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('ix_invoices_status', ['status'], unique=False)
        batch_op.create_index('ix_invoices_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('ix_invoices_issue_date', ['issue_date'], unique=False)
        batch_op.create_index('ix_invoices_due_date', ['due_date'], unique=False)

    # ------------------------------------------------------------------
    # 8. invoice_orders (association table)
    # ------------------------------------------------------------------
    op.create_table('invoice_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['service_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'order_id', name='uq_invoice_orders_invoice_order')
    )

    # ------------------------------------------------------------------
    # 9. invoice_line_items
    # ------------------------------------------------------------------
    op.create_table('invoice_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('line_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('applied_service_id', sa.Integer(), nullable=True),
    sa.Column('labor_entry_id', sa.Integer(), nullable=True),
    sa.Column('parts_used_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['applied_service_id'], ['applied_services.id'], ),
    sa.ForeignKeyConstraint(['labor_entry_id'], ['labor_entries.id'], ),
    sa.ForeignKeyConstraint(['parts_used_id'], ['parts_used.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.create_index('ix_invoice_line_items_invoice_id', ['invoice_id'], unique=False)

    # ------------------------------------------------------------------
    # 10. payments
    # ------------------------------------------------------------------
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('service_order_id', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('external_system', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_invoice_id', ['invoice_id'], unique=False)
        batch_op.create_index('ix_payments_service_order_id', ['service_order_id'], unique=False)
        batch_op.create_index('ix_payments_payment_date', ['payment_date'], unique=False)
        batch_op.create_index('ix_payments_payment_type', ['payment_type'], unique=False)

    # ------------------------------------------------------------------
    # 11. notifications
    # ------------------------------------------------------------------
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'is_read'], unique=False)
        batch_op.create_index('ix_notifications_type', ['notification_type'], unique=False)
        batch_op.create_index('ix_notifications_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # --- notifications ---
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_created_at')
        batch_op.drop_index('ix_notifications_type')
        batch_op.drop_index('ix_notifications_user_read')

    op.drop_table('notifications')

    # --- payments ---
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_payment_type')
        batch_op.drop_index('ix_payments_payment_date')
        batch_op.drop_index('ix_payments_service_order_id')
        batch_op.drop_index('ix_payments_invoice_id')

    op.drop_table('payments')

    # --- invoice_line_items ---
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.drop_index('ix_invoice_line_items_invoice_id')

    op.drop_table('invoice_line_items')

    # --- invoice_orders ---
    op.drop_table('invoice_orders')

    # --- invoices ---
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_invoices_due_date')
        batch_op.drop_index('ix_invoices_issue_date')
        batch_op.drop_index('ix_invoices_customer_id')
        batch_op.drop_index('ix_invoices_status')

    op.drop_table('invoices')

    # --- labor_entries ---
    with op.batch_alter_table('labor_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_labor_entries_work_date')
        batch_op.drop_index('ix_labor_entries_tech_id')
        batch_op.drop_index('ix_labor_entries_order_item_id')

    op.drop_table('labor_entries')

    # --- parts_used ---
    with op.batch_alter_table('parts_used', schema=None) as batch_op:
        batch_op.drop_index('ix_parts_used_inventory_item_id')
        batch_op.drop_index('ix_parts_used_order_item_id')

    op.drop_table('parts_used')

    # --- applied_services ---
    with op.batch_alter_table('applied_services', schema=None) as batch_op:
        batch_op.drop_index('ix_applied_services_price_list_item_id')
        batch_op.drop_index('ix_applied_services_order_item_id')

    op.drop_table('applied_services')

    # --- service_notes ---
    with op.batch_alter_table('service_notes', schema=None) as batch_op:
        batch_op.drop_index('ix_service_notes_order_item_id')

    op.drop_table('service_notes')

    # --- service_order_items ---
    op.drop_table('service_order_items')

    # --- service_orders ---
    with op.batch_alter_table('service_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_orders_is_deleted'))
        batch_op.drop_index('ix_service_orders_assigned_tech_id')
        batch_op.drop_index('ix_service_orders_date_received')
        batch_op.drop_index('ix_service_orders_customer_id')
        batch_op.drop_index('ix_service_orders_status')

    op.drop_table('service_orders')
    # ### end Alembic commands ###
